export const background = {
  backgroundColors: {
    primary: "bg-slate-900",
    secondary: "bg-slate-800",
    contrast: "bg-slate-700",
    accent: "bg-red-900",
    success: "bg-green-900",
    warning: "bg-yellow-900",
    info: "bg-blue-900",
    muted: "bg-gray-900",
    current: "bg-current",
    black: "bg-black",
    white: "bg-white",
    gray: "bg-gray-300",
    red: "bg-red-500",
    yellow: "bg-yellow-500",
    green: "bg-green-500",
    blue: "bg-blue-500",
    indigo: "bg-indigo-500",
    danger: "bg-red-500",
    roles: {
      werewolf: "bg-red-700",
      villager: "bg-blue-500",
      seer: "bg-yellow-500",
      doctor: "bg-green-500",
      hunter: "bg-purple-500",
    },
  },
  backgroundSize: {
    auto: "bg-auto",
    cover: "bg-cover",
    contain: "bg-contain",
  },
  backgroundPosition: {
    bottom: "bg-bottom",
    center: "bg-center",
    left: "bg-left",
    "left-bottom": "bg-left-bottom",
    "left-top": "bg-left-top",
    right: "bg-right",
    "right-bottom": "bg-right-bottom",
    "right-top": "bg-right-top",
    top: "bg-top",
  },
  backgroundImage: {
    none: "bg-none",
    grandientToT: "bg-gradient-to-t",
    grandientToB: "bg-gradient-to-b",
    grandientToTL: "bg-gradient-to-tl",
    grandientToTR: "bg-gradient-to-tr",
    grandientToBL: "bg-gradient-to-bl",
    grandientToBR: "bg-gradient-to-br",
  },
  backgroundRepeat: {
    repeat: "bg-repeat",
    "no-repeat": "bg-no-repeat",
    repeatX: "bg-repeat-x",
    repeatY: "bg-repeat-y",
    "repeat-round": "bg-repeat-round",
    "repeat-space": "bg-repeat-space",
    inherit: "bg-inherit",
  },
  backgroundAttachment: {
    local: "bg-local",
    scroll: "bg-scroll",
    fixed: "bg-fixed",
  },
};
