export const border = {
  borderColors: {
    primary: "border-slate-700",
    accent: "border-red-700",
    muted: "border-slate-800",
    danger: "border-red-700",
    success: "border-green-700",
    warning: "border-yellow-700",
    info: "border-blue-700",
    secondary: "border-gray-700",
    transparent: "border-transparent",
    current: "border-current",
    black: "border-black",
    white: "border-white",
    gray: "border-gray-300",
    red: "border-red-500",
    yellow: "border-yellow-500",
    green: "border-green-500",
    blue: "border-blue-500",
    indigo: "border-indigo-500",
  },
  borderWidths: {
    default: "border",
    0: "border-0",
    2: "border-2",
    4: "border-4",
    8: "border-8",
  },
  borderRadius: {
    none: "rounded-none",
    sm: "rounded-sm",
    DEFAULT: "rounded",
    md: "rounded-md",
    lg: "rounded-lg",
    xl: "rounded-xl",
    "2xl": "rounded-2xl",
    full: "rounded-full",
  },
  borderStyle: {
    solid: "border-solid",
    dashed: "border-dashed",
  },
};
